{
	"_Type": "Action.Type.RestService.SendRequest",
	"ActionResult": {
		"_Name": "postAttachmentData"
	},
	"OnFailure": "/attach/Actions/attachErrorMsg.action",
	"OnSuccess": "/attach/Actions/attachSuccessMsg.action",
	"Target": {
		"Service": "/attach/Services/document_information_extraction.service",
		"Path": "/document/jobs",
		"OutputPath": "/id",
		"RequestProperties": {
			"Method": "POST",
			"Body": "/attach/Rules/fetchAttachmentData.js",
			"FetchCSRF": false
		}
	}
}